### ISSUE TITLE
Service worker: Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by peterpeterparker** [deckgo/deckdeckgo-starter#33]
Sometimes after a redeploy, the error "Service worker: Uncaught SyntaxError: Unexpected token <" at runtime is catcher by Google Chrome

**Comment by peterpeterparker** [comment]
According https://github.com/vuejs-templates/pwa/issues/165 the problem might be the fact that there was no `<base href="/" />` defined in the `<head/>`

I have added it to the starter and DeckDeckGo website too, I keep the issue open to have an eye on it

**Comment by peterpeterparker** [comment]
I opened an issue in Workbox https://github.com/GoogleChrome/workbox/issues/1902 and the awesome @jeffposnick provided the solution :)

**Comment by peterpeterparker** [comment]
@Dellos7 and @sansan88 you might be interested to reproduce the same commit in your presentation which are online and the rebuild and deploy them again, a really nice fix

Fix service worker refresh -> https://github.com/deckgo/deckdeckgo-starter/commit/456159e94039eaddb6f51b71a325eb69db250d41

**Comment by PaulNicolasHunter** [comment]
have a look at this too, seems like the problem was with the env, 
https://stackoverflow.com/questions/62521058/uncaught-syntaxerror-unexpected-token-when-using-create-react-app-develop-m
you might first need to un-register the service by opening that web-app and going to application tab.
follow this for it:
https://stackoverflow.com/questions/33704791/how-do-i-uninstall-a-service-worker.

**Comment by peterpeterparker** [comment]
Thanks for the tips 👍

**Comment by arul0807** [comment]
> According https://github.com/vuejs-templates/pwa/issues/165 the problem might be the fact that there was no `<base href="/" />` defined in the `<head/>`
> 
> I have added it to the starter and DeckDeckGo website too, I keep the issue open to have an eye on it

Some time it happened. How to reproduce the issue
